rule_dict = {
    "kay": "ack",
    "correct": "affirm",
    "right": "affirm",
    "ye": "affirm",
    "yea": "affirm",
    "yeah": "affirm",
    "yes": "affirm",
    "perfect": "affirm",
    "mmhm": "affirm",
    "huh": "affirm",
    "bye": "bye",
    "goodbye": "bye",
    "stop": "bye",
    "do": "confirm",
    "does": "confirm",
    "is": "confirm",
    "serve": "confirm",
    "dont": "deny",
    "wrong": "deny",
    "change": "deny",
    "not": "deny",
    "hello": "hello",
    "hi": "hello",
    "halo": "hello",
    "afghan": "inform",
    "african": "inform",
    "asian": "inform",
    "american": "inform",
    "vietnamese": "inform",
    "portuguese": "inform",
    "spanish": "inform",
    "italian": "inform",
    "thai": "inform",
    "turkish": "inform",
    "indian": "inform",
    "british": "inform",
    "gastropub": "inform",
    "food": "inform",
    "hungarian": "inform",
    "crossover": "inform",
    "serves": "inform",
    "serving": "inform",
    "cheap": "inform",
    "expensive": "inform",
    "moderate": "inform",
    "moderately": "inform",
    "priced": "inform",
    "part": "inform",
    "town": "inform",
    "center": "inform",
    "east": "inform",
    "west": "inform",
    "south": "inform",
    "north": "inform",
    "looking": "inform",
    "im": "inform",
    "matter": "inform",
    "no": "negate",
    "and": "null",
    "breathing": "null",
    "cough": "null",
    "inaudible": "null",
    "knocking": "null",
    "noise": "null",
    "music": "null",
    "sigh": "null",
    "system": "null",
    "tv_noise": "null",
    "static": "null",
    "sil": "null",
    "um": "null",
    "uh": "null",
    "unintelligible": "null",
    "back": "repeat",
    "again": "repeat",
    "repeat": "repeat",
    "another": "reqalts",
    "else": "reqalts",
    "anything": "reqalts",
    "any": "reqalts",
    "about": "reqalts",
    "how": "reqalts",
    "more": "reqmore",
    "ok": "request",
    "okay": "request",
    "address": "request",
    "phone": "request",
    "what": "request",
    "whats": "request",
    "post": "request",
    "telephone": "request",
    "area": "request",
    "can": "request",
    "give": "request",
    "could": "request",
    "location": "request",
    "type": "request",
    "start": "restart",
    "over": "restart",
    "thank": "thankyou",
    "thanks": "thankyou",
    "great": "thankyou",
    "you": "thankyou"
}

count_dict = {
    "ack": 0,  # acknowledgment
    "affirm": 0,  # positive confirmation
    "bye": 0,  # greeting at the end of the dialog
    "confirm": 0,  # check if given information confirms to query
    "deny": 0,  # reject system suggestion
    "hello": 0,  # greeting at the start of the dialog
    "inform": 0,  # state a preference or other information
    "negate": 0,  # negation
    "null": 0,  # noise or utterance without content
    "repeat": 0,  # ask for repetition
    "reqalts": 0,  # request alternative suggestions
    "reqmore": 0,  # request more suggestions
    "request": 0,  # ask for information
    "restart": 0,  # attempt to restart the dialog
    "thankyou": 0,  # express thanks
}
